# Welcome to Jekyll!
#

# Site settings
title: Constitución Abierta
description: www.constitucionabierta.cl
owner: CIWS # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: mvargas@pacha.hk
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/ciwschile
  facebook-official: https://facebook.com/ciwschile

# Build settings
markdown: kramdown
#sass:
#  style: compressed
